env:
  - CODECOV_TOKEN="47165ff1-d005-4427-8f2c-c64bd3fa5200"
# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.1

# Define an environment variable
env:
  - SYMFONY_VERSION="dev-master" DB=mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml

# Run script
script:
  - phpunit tests
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
