<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMmdoegx\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMmdoegx/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMmdoegx.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMmdoegx\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerMmdoegx\appTestDebugProjectContainer([
    'container.build_hash' => 'Mmdoegx',
    'container.build_id' => 'f248002f',
    'container.build_time' => 1551808994,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMmdoegx');
