<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJqtlium\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJqtlium/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJqtlium.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJqtlium\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJqtlium\appDevDebugProjectContainer([
    'container.build_hash' => 'Jqtlium',
    'container.build_id' => '2d7f466b',
    'container.build_time' => 1551807222,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJqtlium');
